function ww:book/init

data modify block 0 0 0 Items[0].tag.title set value '{"text":"選擇職業"}'
data modify block 0 0 0 Items[0].tag.display.Name set value '{"text":"選擇職業","color":"gold","bold":true,"italic":false}'

# Page 1: Instructions and All Roles
data modify block 0 0 0 Items[0].tag.pages append value '[{"text":"請選擇你猜測的職業：\\n\\n","color":"black"},{"text":"[預言家]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 201"}},{"text":" "},{"text":"[女巫]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 202"}},{"text":" "},{"text":"[獵人]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 203"}},{"text":"\\n"},{"text":"[騎士]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 204"}},{"text":" "},{"text":"[守衛]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 205"}},{"text":" "},{"text":"[丘比特]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 206"}},{"text":"\\n"},{"text":"[盜賊]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 207"}},{"text":" "},{"text":"[忍者]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 208"}},{"text":" "},{"text":"[人魚]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 209"}},{"text":"\\n"},{"text":"[掘墓者]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 210"}},{"text":" "},{"text":"[偵探]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 211"}},{"text":" "},{"text":"[詐欺師]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 212"}},{"text":"\\n"},{"text":"[抖S教主]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 214"}},{"text":" "},{"text":"[抖M教徒]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 213"}},{"text":"\\n"},{"text":"[色狼]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 215"}},{"text":" "},{"text":"[村民]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 216"}},{"text":"\\n"},{"text":"[怨靈]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 217"}},{"text":" "},{"text":"[巫毒女孩]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 218"}},{"text":" "},{"text":"[蠱惑師]","underlined":true,"clickEvent":{"action":"run_command","value":"/trigger voteTrigger set 219"}},{"text":"\\n\\n"},{"text":"[ 取消選擇 ]","color":"red","clickEvent":{"action":"run_command","value":"/function ww:item/skill/assassinate"}}]'

data modify block 0 0 0 Items[0].tag.vote set value 1b
data modify block 0 0 0 Items[0].tag.assassin_choose set value 1b

loot give @s mine 0 0 0 air{drop_contents:true}