execute if entity @p[tag=thiefTarget,tag=wolf,tag=bads,tag=!bloody,tag=!white,tag=!hijack,tag=!snow,tag=!alpha,tag=!rage,tag=!black,tag=!bomb] run function ww:role/thief/steal/wolf
execute if entity @p[tag=thiefTarget,tag=wolf,tag=white,tag=bads] run function ww:role/thief/steal/whitewolf
execute if entity @p[tag=thiefTarget,tag=wolf,tag=black,tag=bads] run function ww:role/thief/steal/blackwolf
execute if entity @p[tag=thiefTarget,tag=wolf,tag=snow,tag=bads] run function ww:role/thief/steal/snowwolf
execute if entity @p[tag=thiefTarget,tag=villager,tag=goods] run function ww:role/thief/steal/villager
execute if entity @p[tag=thiefTarget,tag=seer,tag=goods] run function ww:role/thief/steal/seer
execute if entity @p[tag=thiefTarget,tag=hunter,tag=goods] run function ww:role/thief/steal/hunter
execute if entity @p[tag=thiefTarget,tag=witch,tag=goods] run function ww:role/thief/steal/witch
execute if entity @p[tag=thiefTarget,tag=ninja,tag=goods] run function ww:role/thief/steal/ninja
execute if entity @p[tag=thiefTarget,tag=trickster,tag=goods] run function ww:role/thief/steal/trickster
execute if entity @p[tag=thiefTarget,tag=siren,tag=goods] run function ww:role/thief/steal/siren
execute if entity @p[tag=thiefTarget,tag=masochist,tag=goods] run function ww:role/thief/steal/masochist
execute if entity @p[tag=thiefTarget,tag=sadist,tag=goods] run function ww:role/thief/steal/sadist
execute if entity @p[tag=thiefTarget,tag=cupid,tag=goods] run function ww:role/thief/steal/cupid
execute if entity @p[tag=thiefTarget,tag=wraith,tag=wraiths] run function ww:role/thief/steal/wraith
execute if entity @p[tag=thiefTarget,tag=voodoo,tag=wraiths] run function ww:role/thief/steal/voodoo
execute if entity @p[tag=thiefTarget,tag=digger,tag=goods] run function ww:role/thief/steal/digger
execute if entity @p[tag=thiefTarget,tag=wolf,tag=hijack,tag=bads] run function ww:role/thief/steal/hijackwolf
execute if entity @p[tag=thiefTarget,tag=knight,tag=goods] run function ww:role/thief/steal/knight
execute if entity @p[tag=thiefTarget,tag=wolf,tag=alpha,tag=bads] run function ww:role/thief/steal/alphawolf
execute if entity @p[tag=thiefTarget,tag=guardian,tag=goods] run function ww:role/thief/steal/guardian
execute if entity @p[tag=thiefTarget,tag=bewitcher,tag=wraiths] run function ww:role/thief/steal/bewitcher
execute if entity @p[tag=thiefTarget,tag=detective,tag=goods] run function ww:role/thief/steal/detective
execute if entity @p[tag=thiefTarget,tag=hentai,tag=goods] run function ww:role/thief/steal/hentai
execute if entity @p[tag=thiefTarget,tag=wolf,tag=rage,tag=bads] run function ww:role/thief/steal/ragewolf
execute if entity @p[tag=thiefTarget,tag=thief,tag=goods] run function ww:role/thief/steal/thief
execute if entity @p[tag=thiefTarget,tag=wolf,tag=bomb,tag=bads] run function ww:role/thief/steal/bombwolf
execute if entity @p[tag=thiefTarget,tag=wolf,tag=bloody,tag=bads] run function ww:role/thief/steal/bloodywolf